### ISSUE TITLE
Episode 8: crop raster data

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#1]
There are several things that need to be improved: 

- [ ] The data description should be updated;
- [ ] Both raster/vector will come from the open-source, therefore need to be cropped with bounding box 
- [ ] The Bounding box visualization should use a `non-filled` box. We should also bear in mind that some people may have difficulty reading the color;
- [ ] We should integrate original E6: reprojection 
- [ ] There need to be an introduction in raster -> raster reprojection?  We can try rasterize a vector (crop fields polygons), keep its crs, then reproject to the S2 image CRS
- [ ] The raster/PDOK_vector overlay should be visualized 
- [ ] Also teach the data exporting in this episode.

**Comment by SarahAlidoost** [comment]
I found this [documentation](https://rasterio.readthedocs.io/en/latest/topics/features.html#vector-features) using `rasterio`  to convert vector to raster, but I didn't use it as it makes the lesson lengthy and complicated.
