### ISSUE TITLE
Update index.md

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#101]
- [x] General intro of the use case of this workshop
- [ ] A diagram of the data processing workflow (as we had in the [slides](https://github.com/esciencecenter-digital-skills/2023-10-10-ds-geospatial/blob/main/files/Geospatial_python_workshop.pdf)?)
- [x] Upload datasets to figshare and update the dataset links (i.e. ../learners/setup.md)

**Comment by Morrizzzzz** [comment]
Creating the diagram would be something we do at the end. I do have a good draft, but things can change.

**Comment by rogerkuou** [comment]
Most solved by PRF #107. Remaining issue transferred to #109
