### ISSUE TITLE
Episode 5: Raster data access/retrieval episode 

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#2]
We would like to start the practical part of the lesson with this episode. Then in the later episodes the retrieved data can be used.

To Dos:

- Update the searching creteria of image data to make it consistent with the course setup, keep in mind requirements of other episodes. The item should: 
  - Overlap with the AoI bounding box 
  - No cloud in AoI 
  - Some cloud else where 
  - some missing data 
  - Preferably in summer
- A backup data should be uploaded to Figshare in case of skipping this episode

**Comment by fnattino** [comment]
Leaving the second part for a dedicated issue: #12
