### ISSUE TITLE
data file not found error

### ISSUE THREAD

**Issue by cpranav93** [esciencecenter-digital-skills/geospatial-python#24]
In episode 08, in the following code:
 
Load the polygons of the crop fields:
cf_boundary_crop = gpd.read_file("data/crop_fields/cf_boundary_crop.shp")

The data file is not being created in any prior episode. In episode 07,  we have created file with the following:
cropfield_crop.to_file('cropped_field.shp')

Is this the same file refered to in episode 08? 

Same issue in episode 08, Exercise: Select the raster data within crop fields

**Comment by cpranav93** [comment]
Also the following file is needed for the section on 'Crop raster data with a geometry buffer':
groundwater_monitoring_well.shp

**Comment by cpranav93** [comment]
Some basic issues with files have been fixed. However points still to be addressed:
1) Groundwater_monitoring_well.shp and dikes.shp are both not created apriori and not easily available. 
2) The current data-set available online is different from the example given in the episode.

Overall, I think we have to rethink what examples to use and how much data we want to use. @rogerkuou, maybe we can discuss this?

**Comment by rogerkuou** [comment]
The data problem related to wells is solved.

However the waterway data seem to have corrupted coordinates, see #27
