### ISSUE TITLE
Loading the crop fields vector data is too slow

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#32]

**Comment by fnattino** [comment]
`geopandas.read_file` accepts the arguments `bbox, `mask`, and `rows` to load only portion of the data into memory. Not sure whether any of these options speeds up the loading of the dataset (one might still need to loop over all features before filtering) - but we could check whether at least one of these arguments helps. At least they should reduce the memory requirements..

**Comment by fnattino** [comment]
[`read_file` docs](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html#geopandas.read_file)

**Comment by rogerkuou** [comment]
We can try to make the participants download the data before hand, and load it partly with e.g. `bbox`

**Comment by rogerkuou** [comment]
Made a test to profile the memory usage and performance of three scenarios:

1. load all from local. clock time: 1m24.2s. memory increment: 1686.69 MiB
```python
cf_boundary = gpd.read_file("../data/brpgewaspercelen_definitief_2020.gpkg")
```



2. load with bbox from local. clock time: 1.4s. memory increment: 20.68 MiB
```python
cf_boundary = gpd.read_file("../data/brpgewaspercelen_definitief_2020.gpkg", ,bbox=bbox)
```



3. load with bbox from remote. clock time: 42.9s. memory increment: 1016.53 MiB
```python
cf_boundary = gpd.read_file("../data/brpgewaspercelen_definitief_2020.gpkg", ,bbox=bbox)
```

The clock time is counted with the Jupyter Notebook. Mem profiling with the `memit` magic command.
