### ISSUE TITLE
Ep 8: Image seems to be mirrored

### ISSUE THREAD

**Issue by Peter9192** [esciencecenter-digital-skills/geospatial-python#46]
In this example, the first image seems to be mirrored somehow:

![image](https://user-images.githubusercontent.com/17080502/184167202-63d68b65-4f96-49ee-a0cc-7d4682f0ab94.png)

I guess its due to `ax1.set_ylim([ymin, ymax])`. For `imshow` is organized as top to bottom, using `ax1.set_ylim([ymax, ymin])` should fix it.

**Comment by fnattino** [comment]
Thanks a lot @Peter9192 for pointing this out!  This issue should be fixed by @rogerkuou  in #45 .
