### ISSUE TITLE
Download speed for new shapefile datasets from pdok is too slow

### ISSUE THREAD

**Issue by rbavery** [esciencecenter-digital-skills/geospatial-python#61]
When downloading the datasets with the curl command suggested in the episode setup, it takes over a minute to get to 4% progress (I'm on the US west coast).

```
 curl -L --progress-bar \
 --output brpgewaspercelen_definitief_2020.gpkg "https://service.pdok.nl/rvo/brpgewaspercelen/atom/v1_0/downloads/brpgewaspercelen_definitief_2020.gpkg" \
 --output brogmwvolledigeset.zip "https://service.pdok.nl/bzk/brogmwvolledigeset/atom/v2_1/downloads/brogmwvolledigeset.zip" \
 --output status_vaarweg.zip "https://geo.rijkswaterstaat.nl/services/ogc/gdr/vaarweginformatie/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=status_vaarweg&outputFormat=SHAPE-ZIP"
```
from https://esciencecenter-digital-skills.github.io/geospatial-python/setup.html

I think we need to find a solution for this. Ideally, download of these data would only take at most a minute. Some solutions:

* move the data to a zenodo or some other data hosting solution that replicates the data to multiple regions
* decrease dataset size, host in a single location

I'm not sure what the cost implications of these different options are. Before when I used figshare for the small raster datasets, I think we were around 300Mb hosted in a single location and it took about a minute to download on the east coast and west coast.

What do you think @fnattino @rogerkuou ?

also it looks like this file is the culprit, it's half a Gb: [brpgewaspercelen_definitief_2020.gpkg](https://service.pdok.nl/rvo/brpgewaspercelen/atom/v1_0/downloads/brpgewaspercelen_definitief_2020.gpkg)

**Comment by raar1** [comment]
I had a look at the metadata for the crop dataset [here](https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/b812a145-b4fe-4331-8dc6-d914327a87ff?tab=general) and it seems to list three licenses:
<http://creativecommons.org/publicdomain/mark/1.0/deed.nl>
<http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply>
<http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations>

**Comment by fnattino** [comment]
I see @rbavery, indeed taking it so long to download is not really acceptable. Downloading the dataset you have created from figshare takes less than a minute here as well, so we can go ahead and use this as source of the vector data (and really thanks a lot for checking the licenses @raar1!). Do you agree @rogerkuou ?
