### ISSUE TITLE
Polish up the pre-requisite of the course

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#62]
During the 2022-11-21 workshop, we observed confusion on the pre-requisite of the Python level. Some people with more advanced Python knowledge find explaining basic Python concepts can be time-wasting, while others find the pre-requisite is not clearly mentioned. 

We need a more explicit list to specify the pre-requisite.

**Comment by cpranav93** [comment]
This does not seem to be part of the github repo. Where do we add or modify this?

**Comment by fnattino** [comment]
This information lives in the workshop metadata repository: https://github.com/esciencecenter-digital-skills/workshop-metadata/blob/main/ds-geospatial-python/who.md

I feel we did not encounter issues on this at ITC, where participants were more homogeneous in terms of Python expertise, so maybe a bit more clarity on who the target audience is might help.
