### ISSUE TITLE
Workbench migration

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#81]
- [x] Figures reorganization
- [x] Setup instruction with conda env file
- [ ] ~~Intruction part can refer to [geospatial concept lesson](https://datacarpentry.org/organization-geospatial/04-geo-landscape.html)~~

**Comment by fnattino** [comment]
Closed by https://github.com/carpentries-incubator/geospatial-python/pull/158
