### ISSUE TITLE
Make a document for narrative

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#89]
Create a MarkDown file to document the narrative story of the Forest Fire use case.
Upload this notebook to the [notebooks diectory](https://github.com/esciencecenter-digital-skills/geospatial-python/tree/notebooks/notebooks).

**Comment by fnattino** [comment]
In the narrative we have discussed yesterday, we envisioned the parallel raster episode to show how to speed up the slope calculation on the DEM. I have realised, however, that the calculation of the slope is so optimised in Xarray/Xarray-spatial that for the area considered parallelization has a negligible effect. 

We could slightly modify the narrative for this episode in the following way: the goal remains calculating the slope of the DEM, but we doing it on the original DEM data we see that there is quite some noise. Thus, we want to smoothen the DEM, and we do that with the median filtering. So basically we stay with the same example that we currently have, but we apply it to the raster DEM instead than on an optical image with the goal of reduce the noise/improve smoothness before differentiation. The effect of higher smoothness can also be shown via contour plots (much smoother curves are obtained after the median filter is applied).

What are your thoughts @Morrizzzzz and @rogerkuou ?

**Comment by Morrizzzzz** [comment]
@fnattino that is a pitty.. that thought did indeed cross my mind.., (that gdal and Xarray-spatial have probably already optimized slope already). A way how I smoothened DEMs in the past was to convert it to points and interpolate it into a raster again. It would be interesting to maybe try both approached and compare the differences. However at the same time we should choose the easiest route for now, so doing how you suggest makes a lot of sense.
