### ISSUE TITLE
Update raster related episodes to new narratives

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#90]
In the new episodes order:

- [x] EP5: Satellite data access: Download S2 and DEM data
- [x] EP6: Raster intro
- [x] EP9: Raster data calculation: calculate NDVI from S2 data
- [x] EP10: Parallel computation: compute slope

Issues we have temporary solution and need follow up:
- https://github.com/carpentries-incubator/geospatial-python/issues/120

Issues from upper workflow to see if we can reproduce:
- https://github.com/carpentries-incubator/geospatial-python/issues/153
- https://github.com/carpentries-incubator/geospatial-python/issues/143

Things for consideration:
- https://github.com/carpentries-incubator/geospatial-python/issues/122
- https://github.com/carpentries-incubator/geospatial-python/issues/144
- https://github.com/carpentries-incubator/geospatial-python/issues/145

**Comment by rogerkuou** [comment]
Hi @fnattino,  I realized Zonal Stats should be more vector related. I will move this to #92

**Comment by fnattino** [comment]
Noticed some updates on the STAC endpoint, may adapt slightly the material depending on https://github.com/Element84/earth-search/issues/31
