### ISSUE TITLE
Update vector related episodes with new narratives

### ISSUE THREAD

**Issue by rogerkuou** [esciencecenter-digital-skills/geospatial-python#92]
With the forest fire context:

- [x] EP7 Vector data: load OSM data, narrow down to Rhodes, create buffer from roads, intersection
- [ ] EP8 Crop raster data: crop NDVI results with raster, reproject_match DEM and NDVI
- [ ] EP11: Zonal statistics: Zonal statistics for each slope zones

This should solve the following issues in the upflow:

- https://github.com/carpentries-incubator/geospatial-python/issues/92
- https://github.com/carpentries-incubator/geospatial-python/issues/121

**Comment by fnattino** [comment]
Hey @rogerkuou, are you planning to save a shapefile with the contour of Rhodes in EP5? This might be useful for the search of assets in EP6.

**Comment by rogerkuou** [comment]
Yes there will be. See #93, I used the GADM data and retrieved Rhodes island there.
See the `df_rhodes` variable, do you this it will be proper for satellite image search?

**Comment by rogerkuou** [comment]
Finished EP7 in #105. Transfering the rest to #110 and #111
